name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
        
      - name: Custom ssh action
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ec2-user/earztbrief-backend
            git submodule update --remote
            bash deploy.sh
          host: ${{ secrets.HOST_DNS }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY}}

      # - name: AWS SSM Send-Command
      #   uses: peterkimzz/aws-ssm-send-command@master
      #   id: ssm
      #   with:
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     instance-ids: ${{ secrets.INSTANCE_ID }}

      #     working-directory: /home/ec2-user/earztbrief-backend
      #     command: /bin/sh ./deploy.sh



      